### ISSUE TITLE
Add caching ability

### ISSUE THREAD

**Issue by thomotron** [CocytusServices/akd-client#2]
## Description
Add some kind of cache to lessen the impact of DNS failures. Whether it be a genuine upstream issue, local resolver failure, domain expiration, tinkering with DNS, etc. there really should be a contingency.

Simply having the default `authorized_keys` isn't quite enough, since AKD is supposed to centralise and automate the distribution of the keys.

Possibly have an option to overwrite the existing and/or keep its own?

**Comment by thomotron** [comment]
Will have to consider the ownership implications if run as root for the whole system, depending on where the `authorized_keys` file gets stored.

**Comment by NotActuallyTerry** [comment]
If an option to overwrite `authorized_keys` is implemented, it'd be ideal to wait until #3 is completed so a user can't accidentally lock themselves out.

**Comment by thomotron** [comment]
I'm thinking that unless explicitly overridden, the output file can just mirror the ownership of the containing directory. That'll ease configuration for the usual `~/.ssh/...` scenario.
