### ISSUE TITLE
Implement query from URL

### ISSUE THREAD

**Issue by thomotron** [CocytusServices/akd-client#4]
# Description
Originally a part of the AKD spec before it became a DNS-based thing, there should be a way to query a URL for the keys rather than just having them in DNS.

This would be useful for things such as GitHub `.keys` URLs (e.g. [github.com/thomotron.keys](https://github.com/thomotron.keys)).

**Comment by thomotron** [comment]
Possibly add this in as a different key-value pair type in an AKD/S record (`u=https://...`?). That way you can still have the client verify a signature before accepting it if so desired and piggy-back off of existing infrastructure.

**Comment by NotActuallyTerry** [comment]
> Possibly add this in as a different key-value pair type in an AKD/S record (`u=https://...`?). That way you can still have the client verify a signature before accepting it if so desired and piggy-back off of existing infrastructure.

This feels redundant, as the client would still have to update the DNS record every time they update the HTTPS endpoint. If they already have to base64-encode their `authorized_keys` to sign it, then there's a lot more effort involved to update both DNS and HTTPS when they could just update DNS using AKD/S.

Allowing a client to specify a HTTP(S) URL to query in their config however would be really useful, in regards to handballing the key management off to eg. GitHub.

**Comment by thomotron** [comment]
True, it does seem like something better suited to the client config. That'll at least abstract it away from AKD.
